# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Replace with your package manager
    directory: "/" # Directory containing the manifest file
    schedule:
      interval: "daily" # Frequency of updates
    commit-message:
      prefix: "deps"
    versioning-strategy: "auto" # Default strategy for updates
    open-pull-requests-limit: 10
    cooldown: 
      default-days: 5
      semver-major-days: 10
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      fontawesome:
        patterns:
          - "fortawesome/*"
          - "react-fontawesome"
        update-types:
          - "major"
          - "minor"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      jest:
        patterns:
          - "jest"
          - "jest-environment-jsdom"
          - "@types/jest"
    
